results/average stay time.png results/number of visit.png results/number of visits in each year.png : scripts/Data_visualization.R data/processed_data.csv
	Rscript scripts/Data_visualization.R

data/processed_data.csv: scripts/Data_process.py
	python scripts/Data_process.py